"""CoverImage relationships and constraints

Revision ID: 1ac2aee111f0
Revises: dabc816d9f43
Create Date: 2025-12-26 12:26:50.241126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ac2aee111f0'
down_revision: Union[str, Sequence[str], None] = 'dabc816d9f43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_brief_runs_project_id'), 'brief_runs', ['project_id'], unique=False)
    op.drop_constraint(op.f('brief_runs_project_id_fkey'), 'brief_runs', type_='foreignkey')
    op.create_foreign_key(None, 'brief_runs', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'brief_runs', type_='foreignkey')
    op.create_foreign_key(op.f('brief_runs_project_id_fkey'), 'brief_runs', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_brief_runs_project_id'), table_name='brief_runs')
    # ### end Alembic commands ###
