"""Create cover_images

Revision ID: dabc816d9f43
Revises: 31bbd1949b6a
Create Date: 2025-12-26 11:28:42.549100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dabc816d9f43'
down_revision: Union[str, Sequence[str], None] = '31bbd1949b6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cover_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('brief_run_id', sa.UUID(), nullable=True),
    sa.Column('direction_index', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('size', sa.String(length=32), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brief_run_id'], ['brief_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cover_images_brief_run_id'), 'cover_images', ['brief_run_id'], unique=False)
    op.create_index(op.f('ix_cover_images_project_id'), 'cover_images', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cover_images_project_id'), table_name='cover_images')
    op.drop_index(op.f('ix_cover_images_brief_run_id'), table_name='cover_images')
    op.drop_table('cover_images')
    # ### end Alembic commands ###
